on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: test
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup Go 1.17.8
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.8
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Vet
      run: go vet ./...
    - name: Test
      run: go test ./...
